### ISSUE TITLE
create guidelines for appropriate GitHub topics for each lesson

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/organization#3]
For official lessons, we had developed a spreadsheet and some general guidelines for GitHub topics to use: 

- https://github.com/carpentries/maintainer-RFCs/issues/5
- [GitHub topics spreadsheet](https://docs.google.com/spreadsheets/d/1ftV5L2C01aeHrMTWG0WWVm3MSeHMFZOEKw2a7ing138/edit#gid=0)

We need to develop something similar for the Carpentries Incubator to standardize the use of GitHub topics within the organization.

**Comment by tobyhodges** [comment]
Inspired by the resources listed above, I suggest the following guidelines for topic tags:

| category | example | number | description |
|----------|----------|--------|------|
| lesson | `lesson` | 1 | the type of repo. this needs to be `lesson` for the lesson to be listed on the Community Developed Lessons page |
| location | `carpentries-incubator` | 1 | `carpentries-incubator` or `carpentrieslab` |
| language | `español` | >0 | the language(s) the lesson is available in. should be present for every lesson repo |
| stage | `alpha` | 1 | the current development stage for the lesson. See [chapter 7 of the curriculum development handbook](https://cdh.carpentries.org/the-lesson-life-cycle.html) for more info. |
| domain | `microbial-ecology` | 1-2 | the high-level domain(s) of the lesson, for a general categorisation |
| tools | `python` | 1-3 | the tool(s) taught in the lesson |
| skills | `taxonomic-classification` | 1-3 | the main skill(s) taught in the lesson |

I guess it would be helpful to have a publicly-visible sheet of all currently-used topic tags, including a copy of the table above.

**Comment by ErinBecker** [comment]
Seconding the idea of having a publicly-visible sheet of topic tags! If you want to put this in as a PR to the handbook (not sure whether it would be better in the CDH or the overall Carpentries Handbook), I'd be happy to review and merge.

**Comment by tobyhodges** [comment]
Thanks Erin. I'll make a PR, with the table above and a link to the GSheet of tags, to the CDH. I'll tag François for a review there so he can suggest changes/additions to the table I've prepared so far.

**Comment by ErinBecker** [comment]
Sounds like a great plan. Thanks Toby!

**Comment by tobyhodges** [comment]
This was addressed in https://github.com/carpentries/curriculum-development/pull/58
