### ISSUE TITLE
Expanding requirements for inclusion in Carpentries Incubator

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/organization#5]
The README of https://github.com/carpentries-incubator/proposals currently reads

> ## What are the requirements for being included in The Carpentries Incubator?
> 
> * Your lesson must use our [lesson template][lesson-template] and conform to our [Code of Conduct][coc]. You can use the [lesson example](https://carpentries.github.io/lesson-example/) ([GitHub Repo](https://github.com/carpentries/lesson-example/)) to learn more about how to use our lesson template.
> * Your lesson is licensed [CC-BY][cc-by] or [CC-0][cc-0] (or you agree to have your lesson so licensed).
> * (Recommended) Your lesson follows The Carpentries approach to curriculum development detailed in our [Curriculum Development Handbook][cdh].

I propose to expand this section slightly, to address newly-proposed lessons as well as pre-existing material, and add two more requirements:

> ## What are the requirements for being included in The Carpentries Incubator?
> 
> **For all proposals:**
> * **Your lesson/proposed topic should be distinct from existing official and community lessons (in domain of expertise, tools and skills taught/used, target audience, etc). If this is not the case, we recommend you collaborate with the authors/maintainers of those existing materials.**
> 
> **For pre-existing lesson material to be transferred into The Carpentries Incubator:**
> * Your lesson must use our [lesson template][lesson-template] and conform to our [Code of Conduct][coc]. You can use the [lesson example](https://carpentries.github.io/lesson-example/) ([GitHub Repo](https://github.com/carpentries/lesson-example/)) to learn more about how to use our lesson template.
> * Your lesson is licensed [CC-BY][cc-by] or [CC-0][cc-0] (or you agree to have your lesson so licensed).
> * **The current life-cycle stage of your lesson is labeled correctly. See [Chapter 7 of the Curriculum Development Handbook for details](https://cdh.carpentires.org/the-lesson-life-cycle.html#overview-and-definitions). The Curriculum Team can help you identify the appropriate stage for your lesson while processing your proposal.**
> * (Recommended) Your lesson follows The Carpentries approach to curriculum development detailed in our [Curriculum Development Handbook][cdh].

Posting this here for discussion and will update the README based on any conclusions. 

[updated to implement change suggested by @ErinBecker in the comments.]

[cc-0]: https://creativecommons.org/share-your-work/public-domain/cc0/
[cc-by]: https://creativecommons.org/licenses/by/4.0/
[cdh]: https://cdh.carpentries.org/
[carpentries-lab]: https://github.com/carpentrieslab/proposals
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view

**Comment by ErinBecker** [comment]
@tobyhodges - I like this expansion of requirements. My only change would be to rephrase the "is your current stage" bullet point so that it reads as a requirement rather than a question, to match the rest of the bullets.

**Comment by tobyhodges** [comment]
To support the first point about discouraging new lessons on existing topics, I think I will add links to the _Community Developed Lessons_ page and the open Issues of this repository. That should help visitors judge their proposal against this criterion.

**Comment by tobyhodges** [comment]
These changes are implemented in https://github.com/carpentries-incubator/proposals/pull/55
